### ISSUE TITLE
Section 2 - correct citation of definition of gTLD

### ISSUE THREAD

**Issue by rdroms** [Abhayakara/draft-tldr-sutld-ps#77]
Benoit Claise

https://mailarchive.ietf.org/arch/msg/dnsop/_ndo2HnuCIfftGlYkJLbYMZpUPc

gTLD Generic Top-Level Domain, as defined in in section 2 of RFC
7719 [RFC7719]

gTLD is not strictly defined in RFC7719, only TLD

**Comment by wkumari** [comment]
Proposed: 
gTLD  Generic Top-Level Domain (see 'TLD' definition in section 2 of  RFC 7719 [RFC7719])

**Comment by Abhayakara** [comment]
gTLD is actually defined in RFC2240, section 2.   Well, not precisely defined, but I think that's where the term originates.   So I'm proposing that since we already have a reference for TLD from RFC7719 in the previous definition, we include the reference to RFC2240 instead here.  I'll be committing this change, but if y'all disagree I can back it out.

**Comment by rdroms** [comment]
> On Jun 6, 2017, at 3:02 PM, Ted Lemon <notifications@github.com> wrote:
> 
> gTLD is actually defined in RFC2240, section 2. Well, not precisely defined, but I think that's where the term originates. So I'm proposing that since we already have a reference for TLD from RFC7719 in the previous definition, we include the reference to RFC2240 instead here. I'll be committing this change, but if y'all disagree I can back it out.

OK with me.

- Ralph
