### ISSUE TITLE
Stephane Bortzmeyer: IETF-ICANN have a liaison relationship

### ISSUE THREAD

**Issue by Abhayakara** [Abhayakara/draft-tldr-sutld-ps#83]
> * Section 3 says "Use of the registry is inconsistent -- some
> Special-Use Domain Name RFCs specify registry entries, some don't;
> some specify delegation, some don't." There is no inconsistency
> here. RFC 6761 says (in its section 5) that the reservation of a
> Special-Use Domain Name is free to choose the rules regarding
> resolution, as long as they are properly explained.

We could replace the first sentence as follows: "Although the IETF and ICANN do have a liaison relationship through which special-use allocations can be discussed, there exists no formal process for coordinating these allocations."

**Comment by wkumari** [comment]
LGTM. 
Personally I'd drop the "do" in "do have", but I don't feel strongly about this.

**Comment by rdroms** [comment]
I think there's a cut-and-paste error between #83 and #84 (or my browser is confused).

#83 should, I think (based on Ted's first comment) refer to Stephane's first bullet point:

* Section 3 says "No formal coordination process exists between the
IETF and ICANN" This is not true, there is a formal liaison
<https://www.ietf.org/liaison/managers.html> and it is even mentioned
laster, in section 4.1.4. This issue was mentioned during the WGLC
<https://mailarchive.ietf.org/arch/msg/dnsop/OWt8DkBJ_JpIITF-R2YpwEhiwFs>

I've taken the liberty of editing the title of this issue...

**Comment by rdroms** [comment]
Now that I feel better about fixing something broken in the Internet, I agree with the goal of Ted's suggested text and with Warren's editorial suggestion.

**Comment by rdroms** [comment]
Edits completed and committed.
